Create restful_curd.py
Generate SQLite database first.
The above code to handle CRUD operation to SQLite, but if you run this python file and try to access the endpoint(you can try to access localhost:5000/user) you will get the error message similar with
OperationalError: (sqlite3.OperationalError) no such table: user [SQL: u’SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email \nFROM user’]
This error message occurred because you trying to get data from SQLite, but you don’t have SQLite database yet. So In this step we will generate SQLite database first before running our application. You can generate SQLite database based on your model in crud.py using following step.
enter into python interactive shell
First you need to enter into python interactive shell using following command in your terminal:
$ python
2. import db object and generate SQLite database
Use following code in python interactive shell
>>> from crud import db
>>> db.create_all()
And crud.sqlite will be generated inside your flask_tutorial folder.
d. Run flask application
Now after generate sqlite database, we are ready to run our flask application. Run following command from your terminal to run your application.
$ python restful_curd.py